POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "test2",
  "password": "12345678",
  "email": "abc@gmail.com"
}

###
POST http://localhost:3000/sign-in
Content-Type: application/json

{
  "username": "test2",
  "password": "12345678"
}
###
DELETE http://localhost:3000/logout
x-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZmM4N2JiZGFhYjY3MmVhODE3ZDQ4OSIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE2MTA1MjkxNzQsImV4cCI6MTYxMDc4ODM3NH0.ZPeVXwk72BjH60LBZBtNTJ4fZDQEraP2RUj5JjRHjfs

###
POST http://localhost:3000/refresh-token
x-refresh-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZmM4N2JiZGFhYjY3MmVhODE3ZDQ4OSIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE2MTA0NzMyNDksImV4cCI6MTYxMTA3ODA0OX0.TQoHpp7-hBR6qDkDL2XeAzs_eLI_uq9hyHUbq3O8lYY

###
POST http://localhost:3000/forgot-password
Content-Type: application/json

{
  "email": "daonghia04@gmail.com"
}

###
POST  http://localhost:3000/reset-password
Content-Type: application/json

{
  "resetToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhb25naGlhMjQwNEBnbWFpbC5jb20iLCJpYXQiOjE2MTA1MjkyMzQsImV4cCI6MTYxMDUyOTUzNH0.YAmOKsrVD42rk3v5N7D0wMOiAEDjyjV473G_VVimT5o",
  "newPassword": "daonghia240404"
}
###
POST  http://localhost:3000/check-reset-password
Content-Type: application/json

{
  "resetToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhb25naGlhMjQwNEBnbWFpbC5jb20iLCJpYXQiOjE2MTA1MjkyMzQsImV4cCI6MTYxMDUyOTUzNH0.YAmOKsrVD42rk3v5N7D0wMOiAEDjyjV473G_VVimT5o"
}

###
GET  http://localhost:3000/test-auth
x-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZmM4N2JiZGFhYjY3MmVhODE3ZDQ4OSIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE2MTA0NzMzNjEsImV4cCI6MTYxMDQ3MzM5MX0.38N9PCy5sdVcZqjWfl2SjY8IVBAS94VHYY3Ysll6Nlk